[package]
name = "sysroot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
autobins = false
autotests = false

[[bin]]
name = "sysroot"
path = "main.rs"
test = false

[[test]]
name = "e2e_home_export"
path = "tests/e2e_home_export.rs"

[[test]]
name = "e2e_source_targets"
path = "tests/e2e_source_targets.rs"

[[test]]
name = "e2e_setup_tpm_unlock"
path = "tests/e2e_setup_tpm_unlock.rs"

[[test]]
name = "e2e_engine"
path = "tests/e2e_engine.rs"

[[test]]
name = "e2e_system"
path = "tests/e2e_system.rs"

[[test]]
name = "e2e_context"
path = "tests/e2e_context.rs"

[[test]]
name = "e2e_native"
path = "tests/e2e_native.rs"

[[test]]
name = "e2e_catalog"
path = "tests/e2e_catalog.rs"

[dependencies]
sysroot-core.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
tar.workspace = true
toml.workspace = true
toml_edit.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
sysroot-linux.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true
sysroot-engine.workspace = true
sysroot-catalog.workspace = true

[lints]
workspace = true
