[package]
name = "sysroot-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"
doctest = false
test = false

[dependencies]
sysroot-engine.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
